name: Base application setup
description: Setup dependencies and Python environment to run the application in GitHub Actions.

runs:
  using: composite
  steps:
    - name: Setup Poetry
      run: |
        pip3 install "poetry==1.1.6"
        poetry config virtualenvs.create false
      shell: bash
    - name: Install the application and it's dependencies
      run: poetry install
      shell: bash
