name: Base application setup
description: Setup dependencies and Python environment to run the application in GitHub Actions.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Poetry and the application
      run: |
        pip3 install "poetry==1.1.6"
        poetry config virtualenvs.create false
        poetry install
