# Generated by Django 3.2.4 on 2021-06-14 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.entry')),
                ('blurhash', models.CharField(help_text='Blurhash textual representation that can be used for loading placeholders.', max_length=100, null=True, verbose_name='blurhash')),
                ('format', models.CharField(max_length=20, verbose_name='format')),
                ('width', models.PositiveIntegerField(verbose_name='width')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('camera_make', models.CharField(blank=True, max_length=50, null=True, verbose_name='camera maker')),
                ('camera_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='camera model')),
                ('iso_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='ISO value')),
                ('exposure_time', models.FloatField(blank=True, help_text="The shot's exposure time, in seconds.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='exposure time')),
                ('aperture_size', models.FloatField(blank=True, help_text='Aperture / F-Stop value of the shot, in inverse. A value of 4 in this field implies an f-value of f/4.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aperture size')),
                ('focal_length', models.FloatField(blank=True, help_text='Focal length of the camera, in millimeters.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='focal length')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
            bases=('timeline.entry', models.Model),
        ),
    ]
