# Generated by Django 3.2.5 on 2021-07-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_library_default_visibility'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif_digest',
            field=models.CharField(blank=True, help_text='This value is used to map images to their RAW counterparts.', max_length=64, null=True, verbose_name='exif digest value'),
        ),
        migrations.CreateModel(
            name='RawPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exif_digest', models.CharField(blank=True, help_text='This value is used to map images to their RAW counterparts.', max_length=64, null=True, verbose_name='exif digest value')),
                ('file', models.ForeignKey(help_text='File object this handler is responsible for.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storage.file', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='raw_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renditions', related_query_name='rendition', to='gallery.rawphoto', verbose_name='raw source'),
        ),
    ]
