# Generated by Django 3.2.5 on 2021-07-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210709_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawphoto',
            options={'verbose_name': 'raw photo', 'verbose_name_plural': 'raw photos'},
        ),
    ]
