# Generated by Django 3.2.6 on 2021-08-05 12:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_entry_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'default_manager_name': 'active_objects', 'ordering': ['timestamp', 'id'], 'verbose_name': 'timeline entry', 'verbose_name_plural': 'timeline entries'},
        ),
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
