# Generated by Django 3.1.4 on 2021-01-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.entry')),
                ('first_number', models.IntegerField()),
                ('second_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('timeline.entry',),
        ),
        migrations.CreateModel(
            name='FooEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.entry')),
                ('the_string', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('timeline.entry',),
        ),
    ]
