# Generated by Django 3.2.4 on 2021-06-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='default_visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'All logged-in users'), (2, 'Library members'), (3, 'Only library owners')], default=2, help_text='Default visibility value for content where it is not defined.', verbose_name='default visibility'),
        ),
    ]
