name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: ./.github/actions/setup
      - name: Check isort
        run: isort --check .
      - name: Check black
        run: black --check .

  docker:
    runs-on: ubuntu-latest
    needs: lint
    name: Build and publish Docker container
    steps:
      - uses: actions/checkout@v1
      - run: echo "::set-env name=IMAGE::docker.pkg.github.com/$GITHUB_REPOSITORY/server:$(echo ${GITHUB_REF#refs/heads/})"
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.base_ref }}
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker build -t $IMAGE -f docker/Dockerfile .
          docker push $IMAGE
