name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: ./.github/actions/setup
      - name: Check isort
        run: isort --check .
      - name: Check black
        run: black --check .

  docker:
    runs-on: ubuntu-latest
    needs: lint
    name: Build and publish Docker container
    steps:
      - uses: actions/checkout@v1
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/server:$GITHUB_REF -f docker/Dockerfile .
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/server:$GITHUB_REF
