name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: ./.github/actions/setup
      - name: Check isort
        run: isort --check .
      - name: Check black
        run: black --check .

  docker:
    runs-on: ubuntu-latest
    needs: lint
    name: Build and publish Docker container
    steps:
      - uses: actions/checkout@v2
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ github.ref }}:latest
