name: Continuous integration

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      -
        name: Setup project
        uses: ./.github/actions/setup
      -
        name: Check isort
        run: isort --check .
      -
        name: Check black
        run: black --check .

  docker:
    runs-on: ubuntu-latest
    needs: lint
    name: Docker container
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,prefix=
      -
        name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
