name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: ./.github/actions/setup
      - name: Build Sphinx project
        run: |
          cd docs
          make dirhtml
      - name: Deploy to GitHub pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/_build/dirhtml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: GitHub Pages
      url: https://tumpara.github.io/server/
