name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Build and deploy docs
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      -
        name: Setup project
        uses: ./.github/actions/setup
      -
        name: Build Sphinx project
        run: |
          cd docs
          make dirhtml
          touch _build/dirhtml/.nojekyll
      -
        name: Deploy to GitHub pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/_build/dirhtml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
